/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.marvinmessaging;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int compose=0x7f040003;
        public static final int contact_f_name=0x7f040006;
        public static final int contact_form_title=0x7f040005;
        public static final int contact_l_name=0x7f040007;
        public static final int contact_m_num=0x7f040008;
        public static final int contact_submit_button=0x7f040009;
        public static final int message_form_title=0x7f04000a;
        public static final int new_contact=0x7f040000;
        public static final int new_message_body=0x7f04000d;
        public static final int new_message_name=0x7f04000b;
        public static final int new_message_num=0x7f04000c;
        public static final int new_message_submit_button=0x7f04000e;
        public static final int row_name=0x7f040001;
        public static final int row_phone_number=0x7f040002;
        public static final int view_contacts=0x7f040004;
    }
    public static final class layout {
        public static final int contact_list=0x7f020000;
        public static final int contact_list_contextmenu=0x7f020001;
        public static final int contact_row=0x7f020002;
        public static final int main=0x7f020003;
        public static final int new_contact=0x7f020004;
        public static final int new_message=0x7f020005;
    }
    public static final class string {
        public static final int app_name=0x7f030000;
        public static final int contact_form_button=0x7f030007;
        public static final int contact_form_button_edit=0x7f030002;
        public static final int contact_form_button_insert=0x7f030001;
        public static final int contact_form_title=0x7f030006;
        public static final int contact_form_title_edit=0x7f030004;
        public static final int contact_form_title_insert=0x7f030003;
        public static final int message_form_title=0x7f030005;
        public static final int new_message_form_button=0x7f030008;
    }
}
